### PR TITLE
fix: sanity fixes update, fix id

### PR DESCRIPTION
**Pull request by alansoliditydev**
image
@moondao final pull request mate, let's do this quick

### CODE REVIEW

**Comment by alansoliditydev** [comment]
@moondao after fix the code, do `npm run check-sanity`, and you should pass the ci check and can be approved quickly

**Comment by moondao** [comment]
> @moondao after fix the code, do `npm run check-sanity`, and you should pass the ci check and can be approved quickly

please tell me which part code should be fixed?

**Comment by alansoliditydev** [comment]
@moondao you did a good job bro, just remind TrustWallet team to check on us 
image

**Comment by moondao** [comment]
> @moondao you did a good job bro, just remind TrustWallet team to check on us
> image

so now i just need to wait?

**Comment by alansoliditydev** [comment]
yes and remind approver on their pull request https://github.com/trustwallet/assets/pull/6078

**Comment by moondao** [comment]
ok thank you.

**Comment by alansoliditydev** [comment]
@moondao can you remind @catenocrypt or @zachzwei on the pull request, they should approve now because it should be done within a working day lol

**Pull request merged**
